name: Compliance Checks
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - edited
        branches:
            - develop
            - master
            - main
jobs:
    check_pr_description:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: test
              run: |
                  export DESCRIPTION=$(jq '.pull_request.body' $GITHUB_EVENT_PATH)
                  DESCRIPTION="${DESCRIPTION%\"}"
                  DESCRIPTION="${DESCRIPTION#\"}"

                  echo "$DESCRIPTION"

                  python .github/validate_pull_request.py --description "$DESCRIPTION"
